"""empty message

Revision ID: 88757ede04de
Revises: 350cee485d99
Create Date: 2020-04-16 13:44:56.703711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88757ede04de'
down_revision = '350cee485d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###
